// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CandidateEntityPublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        run_uid: {
            type: 'string',
            title: 'Run Uid'
        },
        raw_name: {
            type: 'string',
            title: 'Raw Name'
        },
        entity_type: {
            type: 'string',
            title: 'Entity Type'
        },
        confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confidence'
        },
        canonical_asset_uid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Canonical Asset Uid'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        evidences: {
            items: {
                '$ref': '#/components/schemas/CandidateEvidencePublic'
            },
            type: 'array',
            title: 'Evidences',
            default: []
        }
    },
    type: 'object',
    required: ['uid', 'run_uid', 'raw_name', 'entity_type', 'confidence', 'canonical_asset_uid', 'created_at'],
    title: 'CandidateEntityPublic'
} as const;

export const CandidateEntityUpdateSchema = {
    properties: {
        canonical_asset_uid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Canonical Asset Uid'
        },
        entity_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Type'
        }
    },
    type: 'object',
    title: 'CandidateEntityUpdate'
} as const;

export const CandidateEvidenceCreateSchema = {
    properties: {
        line_id: {
            type: 'string',
            title: 'Line Id'
        },
        quote: {
            type: 'string',
            title: 'Quote'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['line_id', 'quote'],
    title: 'CandidateEvidenceCreate'
} as const;

export const CandidateEvidencePublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        candidate_uid: {
            type: 'string',
            title: 'Candidate Uid'
        },
        line_id: {
            type: 'string',
            title: 'Line Id'
        },
        quote: {
            type: 'string',
            title: 'Quote'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['uid', 'candidate_uid', 'line_id', 'quote', 'reason', 'created_at'],
    title: 'CandidateEvidencePublic'
} as const;

export const CanonicalAssetAliasCreateSchema = {
    properties: {
        alias: {
            type: 'string',
            title: 'Alias'
        }
    },
    type: 'object',
    required: ['alias'],
    title: 'CanonicalAssetAliasCreate'
} as const;

export const CanonicalAssetAliasPublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        asset_uid: {
            type: 'string',
            title: 'Asset Uid'
        },
        alias: {
            type: 'string',
            title: 'Alias'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['uid', 'asset_uid', 'alias', 'created_at'],
    title: 'CanonicalAssetAliasPublic'
} as const;

export const CanonicalAssetCreateSchema = {
    properties: {
        project_uid: {
            type: 'string',
            title: 'Project Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        aliases: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Aliases',
            default: []
        }
    },
    type: 'object',
    required: ['project_uid', 'name', 'type'],
    title: 'CanonicalAssetCreate'
} as const;

export const CanonicalAssetPublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        project_uid: {
            type: 'string',
            title: 'Project Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        aliases: {
            items: {
                '$ref': '#/components/schemas/CanonicalAssetAliasPublic'
            },
            type: 'array',
            title: 'Aliases',
            default: []
        }
    },
    type: 'object',
    required: ['uid', 'project_uid', 'name', 'type', 'description', 'created_at', 'updated_at'],
    title: 'CanonicalAssetPublic'
} as const;

export const CanonicalAssetUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'CanonicalAssetUpdate'
} as const;

export const ExtractionRunCreateSchema = {
    properties: {
        project_uid: {
            type: 'string',
            title: 'Project Uid'
        },
        script_uid: {
            type: 'string',
            title: 'Script Uid'
        },
        step: {
            type: 'integer',
            title: 'Step'
        },
        model_config_dict: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Config Dict'
        }
    },
    type: 'object',
    required: ['project_uid', 'script_uid', 'step'],
    title: 'ExtractionRunCreate'
} as const;

export const ExtractionRunPublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        project_uid: {
            type: 'string',
            title: 'Project Uid'
        },
        script_uid: {
            type: 'string',
            title: 'Script Uid'
        },
        step: {
            type: 'integer',
            title: 'Step'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: ['uid', 'project_uid', 'script_uid', 'step', 'status', 'created_at', 'finished_at'],
    title: 'ExtractionRunPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NormalizedScriptPublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        script_uid: {
            type: 'string',
            title: 'Script Uid'
        },
        version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        content_json: {
            title: 'Content Json'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['uid', 'script_uid', 'version', 'content_json', 'created_at'],
    title: 'NormalizedScriptPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['uid', 'name', 'created_at'],
    title: 'ProjectPublic'
} as const;

export const ScriptCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['name', 'content'],
    title: 'ScriptCreate'
} as const;

export const ScriptDetailPublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        project_uid: {
            type: 'string',
            title: 'Project Uid'
        }
    },
    type: 'object',
    required: ['uid', 'name', 'created_at', 'content', 'project_uid'],
    title: 'ScriptDetailPublic'
} as const;

export const ScriptListPublicSchema = {
    properties: {
        uid: {
            type: 'string',
            title: 'Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['uid', 'name', 'created_at'],
    title: 'ScriptListPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;