// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CandidateEntityPublic = {
    uid: string;
    run_uid: string;
    raw_name: string;
    entity_type: string;
    confidence: (number | null);
    canonical_asset_uid: (string | null);
    created_at: string;
    evidences?: Array<CandidateEvidencePublic>;
};

export type CandidateEntityUpdate = {
    canonical_asset_uid?: (string | null);
    entity_type?: (string | null);
};

export type CandidateEvidenceCreate = {
    line_id: string;
    quote: string;
    reason?: (string | null);
};

export type CandidateEvidencePublic = {
    uid: string;
    candidate_uid: string;
    line_id: string;
    quote: string;
    reason: (string | null);
    created_at: string;
};

export type CanonicalAssetAliasCreate = {
    alias: string;
};

export type CanonicalAssetAliasPublic = {
    uid: string;
    asset_uid: string;
    alias: string;
    created_at: string;
};

export type CanonicalAssetCreate = {
    project_uid: string;
    name: string;
    type: string;
    description?: (string | null);
    aliases?: Array<(string)>;
};

export type CanonicalAssetPublic = {
    uid: string;
    project_uid: string;
    name: string;
    type: string;
    description: (string | null);
    created_at: string;
    updated_at: (string | null);
    aliases?: Array<CanonicalAssetAliasPublic>;
};

export type CanonicalAssetUpdate = {
    name?: (string | null);
    type?: (string | null);
    description?: (string | null);
};

export type ExtractionRunCreate = {
    project_uid: string;
    script_uid: string;
    step: number;
    model_config_dict?: ({
    [key: string]: unknown;
} | null);
};

export type ExtractionRunPublic = {
    uid: string;
    project_uid: string;
    script_uid: string;
    step: number;
    status: (string | null);
    error_message?: (string | null);
    created_at: string;
    finished_at: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NormalizedScriptPublic = {
    uid: string;
    script_uid: string;
    version: (string | null);
    content_json: unknown;
    created_at: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    name: string;
    description?: (string | null);
};

export type ProjectPublic = {
    uid: string;
    name: string;
    description?: (string | null);
    created_at: string;
    updated_at?: (string | null);
};

export type ScriptCreate = {
    name: string;
    content: string;
};

export type ScriptDetailPublic = {
    uid: string;
    name: string;
    created_at: string;
    content: string;
    project_uid: string;
};

export type ScriptListPublic = {
    uid: string;
    name: string;
    created_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AliasesDeleteAliasData = {
    uid: string;
};

export type AliasesDeleteAliasResponse = (unknown);

export type AssetsCreateAssetData = {
    requestBody: CanonicalAssetCreate;
};

export type AssetsCreateAssetResponse = (CanonicalAssetPublic);

export type AssetsReadAssetsData = {
    limit?: number;
    projectUid?: (string | null);
    skip?: number;
    type?: (string | null);
};

export type AssetsReadAssetsResponse = (Array<CanonicalAssetPublic>);

export type AssetsReadAssetData = {
    uid: string;
};

export type AssetsReadAssetResponse = (CanonicalAssetPublic);

export type AssetsUpdateAssetData = {
    requestBody: CanonicalAssetUpdate;
    uid: string;
};

export type AssetsUpdateAssetResponse = (CanonicalAssetPublic);

export type AssetsCreateAssetAliasData = {
    requestBody: CanonicalAssetAliasCreate;
    uid: string;
};

export type AssetsCreateAssetAliasResponse = (CanonicalAssetAliasPublic);

export type CandidatesUpdateCandidateData = {
    requestBody: CandidateEntityUpdate;
    uid: string;
};

export type CandidatesUpdateCandidateResponse = (CandidateEntityPublic);

export type CandidatesDeleteCandidateData = {
    uid: string;
};

export type CandidatesDeleteCandidateResponse = (unknown);

export type CandidatesCreateEvidenceData = {
    requestBody: CandidateEvidenceCreate;
    uid: string;
};

export type CandidatesCreateEvidenceResponse = (CandidateEvidencePublic);

export type EvidencesDeleteEvidenceData = {
    uid: string;
};

export type EvidencesDeleteEvidenceResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (Array<ProjectPublic>);

export type ProjectsReadProjectData = {
    uid: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsCreateProjectScriptData = {
    projectUid: string;
    requestBody: ScriptCreate;
};

export type ProjectsCreateProjectScriptResponse = (ScriptListPublic);

export type ProjectsReadProjectScriptsData = {
    limit?: number;
    projectUid: string;
    skip?: number;
};

export type ProjectsReadProjectScriptsResponse = (Array<ScriptListPublic>);

export type RunsCreateRunData = {
    requestBody: ExtractionRunCreate;
};

export type RunsCreateRunResponse = (ExtractionRunPublic);

export type RunsReadRunData = {
    uid: string;
};

export type RunsReadRunResponse = (ExtractionRunPublic);

export type RunsReadRunCandidatesData = {
    entityType?: (string | null);
    uid: string;
};

export type RunsReadRunCandidatesResponse = (Array<CandidateEntityPublic>);

export type ScriptsReadScriptData = {
    uid: string;
};

export type ScriptsReadScriptResponse = (ScriptDetailPublic);

export type ScriptsReadNormalizedScriptData = {
    uid: string;
    version?: (string | null);
};

export type ScriptsReadNormalizedScriptResponse = (NormalizedScriptPublic);

export type ScriptsReadScriptRunsData = {
    uid: string;
};

export type ScriptsReadScriptRunsResponse = (Array<ExtractionRunPublic>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);