"""add error_message to extraction_run

Revision ID: 2dc6f9764e09
Revises: 7a789382fb0a
Create Date: 2026-01-07 18:14:39.707483

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2dc6f9764e09'
down_revision = '7a789382fb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_run', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_run', 'error_message')
    # ### end Alembic commands ###
