"""add entity extraction tables

Revision ID: 7a789382fb0a
Revises: 1a31ce608336
Create Date: 2026-01-07 13:27:50.199559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7a789382fb0a'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_snapshot',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_artifact_snapshot_run_uid'), 'artifact_snapshot', ['run_uid'], unique=False)
    op.create_table('candidate_entity',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('canonical_asset_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_candidate_entity_canonical_asset_uid'), 'candidate_entity', ['canonical_asset_uid'], unique=False)
    op.create_index(op.f('ix_candidate_entity_run_uid'), 'candidate_entity', ['run_uid'], unique=False)
    op.create_table('candidate_evidence',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_candidate_evidence_candidate_uid'), 'candidate_evidence', ['candidate_uid'], unique=False)
    op.create_table('canonical_asset',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('canonical_asset_project_uid_type_idx', 'canonical_asset', ['project_uid', 'type'], unique=False)
    op.create_index(op.f('ix_canonical_asset_project_uid'), 'canonical_asset', ['project_uid'], unique=False)
    op.create_index(op.f('ix_canonical_asset_run_uid'), 'canonical_asset', ['run_uid'], unique=False)
    op.create_table('extraction_run',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('script_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_extraction_run_project_uid'), 'extraction_run', ['project_uid'], unique=False)
    op.create_index(op.f('ix_extraction_run_script_uid'), 'extraction_run', ['script_uid'], unique=False)
    op.create_table('normalized_script',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('script_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_normalized_script_script_uid'), 'normalized_script', ['script_uid'], unique=False)
    op.create_table('project',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('script',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_script_project_uid'), 'script', ['project_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_project_uid'), table_name='script')
    op.drop_table('script')
    op.drop_table('project')
    op.drop_index(op.f('ix_normalized_script_script_uid'), table_name='normalized_script')
    op.drop_table('normalized_script')
    op.drop_index(op.f('ix_extraction_run_script_uid'), table_name='extraction_run')
    op.drop_index(op.f('ix_extraction_run_project_uid'), table_name='extraction_run')
    op.drop_table('extraction_run')
    op.drop_index(op.f('ix_canonical_asset_run_uid'), table_name='canonical_asset')
    op.drop_index(op.f('ix_canonical_asset_project_uid'), table_name='canonical_asset')
    op.drop_index('canonical_asset_project_uid_type_idx', table_name='canonical_asset')
    op.drop_table('canonical_asset')
    op.drop_index(op.f('ix_candidate_evidence_candidate_uid'), table_name='candidate_evidence')
    op.drop_table('candidate_evidence')
    op.drop_index(op.f('ix_candidate_entity_run_uid'), table_name='candidate_entity')
    op.drop_index(op.f('ix_candidate_entity_canonical_asset_uid'), table_name='candidate_entity')
    op.drop_table('candidate_entity')
    op.drop_index(op.f('ix_artifact_snapshot_run_uid'), table_name='artifact_snapshot')
    op.drop_table('artifact_snapshot')
    # ### end Alembic commands ###
