"""add canonical asset alias

Revision ID: a68c6a85675d
Revises: 2dc6f9764e09
Create Date: 2026-01-07 18:20:36.354459

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a68c6a85675d'
down_revision = '2dc6f9764e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_asset_alias',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_canonical_asset_alias_asset_uid'), 'canonical_asset_alias', ['asset_uid'], unique=False)
    op.drop_column('canonical_asset', 'aliases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_asset', sa.Column('aliases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_canonical_asset_alias_asset_uid'), table_name='canonical_asset_alias')
    op.drop_table('canonical_asset_alias')
    # ### end Alembic commands ###
